In [14]:
import pandas as pd

path = '../data/real_pv/br-pvgen/'
metadata_df = pd.read_csv(path + "metadata.csv")

# print(metadata_df)
inv_cols = ["datetime", "ps_id","total_active_power_w"]
meteo_cols = ["ambient_temperature_celsius", "ghi_irradiance_wm2"]
joined_cols = meteo_cols + inv_cols
meteo_cols += ["datetime", "ps_id"]
result = None
for pv_id in metadata_df['id'].unique():
    inv_filename = path + 'inverter/' + pv_id + '.csv'
    inv_df = pd.read_csv(inv_filename)
    inv_df["datetime"] = pd.to_datetime(inv_df["datetime"])
    inv_df = inv_df.groupby(["datetime", "ps_id"], as_index=False).agg(total_active_power_w=("total_active_power_w", "sum"))
    inv_df = inv_df[inv_cols]
    inv_df = inv_df.set_index(["datetime", "ps_id"])
    
    meteo_filename = path + 'meteorological/' + pv_id + '.csv'
    meteo_df = pd.read_csv(meteo_filename)
    meteo_df["datetime"] = pd.to_datetime(meteo_df["datetime"])
    
    meteo_df = meteo_df[meteo_cols]
    meteo_df = meteo_df.set_index(["datetime", "ps_id"])
    
    common_df = inv_df.join(meteo_df)
          
    if result is None:
        result = common_df
    else:
        result = pd.concat([result, common_df])
    



result

42336
42336
True
True
42336
total_active_power_w              0
ambient_temperature_celsius    1332
ghi_irradiance_wm2             1317
dtype: int64

/tmp/ipykernel_3319999/2141524626.py:21: DtypeWarning: Columns (0: interpolated_keys_ambient_temperature_celsius, 1: interpolated_keys_ghi_irradiance_wm2, 2: interpolated_keys_gri_irradiance_wm2, 3: interpolated_keys_panel_temperature_celsius, 4: interpolated_keys_poa_irradiance_wm2, 5: interpolated_keys_wind_speed_ms) have mixed types. Specify dtype option on import or set low_memory=False.
  meteo_df = pd.read_csv(meteo_filename)

42336
42336
True
True
42336
total_active_power_w             0
ambient_temperature_celsius    827
ghi_irradiance_wm2             827
dtype: int64
42336
42336
True
True
42336
total_active_power_w             0
ambient_temperature_celsius    930
ghi_irradiance_wm2             930
dtype: int64

/tmp/ipykernel_3319999/2141524626.py:14: DtypeWarning: Columns (0: interpolated_keys_internal_temperature_celsius, 1: interpolated_keys_total_active_power_w, 2: interpolated_keys_total_dc_power_w, 3: interpolated_keys_total_reactive_power_var) have mixed types. Specify dtype option on import or set low_memory=False.
  inv_df = pd.read_csv(inv_filename)

42336
42336
True
True
42336
total_active_power_w              0
ambient_temperature_celsius    6547
ghi_irradiance_wm2             6547
dtype: int64
40800
40800
True
True
40800
total_active_power_w              0
ambient_temperature_celsius    2323
ghi_irradiance_wm2             2323
dtype: int64
38112
35520
True
True
38112
total_active_power_w              0
ambient_temperature_celsius    4390
ghi_irradiance_wm2             4390
dtype: int64
38112
38112
True
True
38112
total_active_power_w              0
ambient_temperature_celsius    3545
ghi_irradiance_wm2             3545
dtype: int64
38016
37632
True
True
38016
total_active_power_w              0
ambient_temperature_celsius    7330
ghi_irradiance_wm2             7330
dtype: int64
35040
35040
True
True
35040
total_active_power_w             0
ambient_temperature_celsius    401
ghi_irradiance_wm2             401
dtype: int64
34848
34848
True
True
34848
total_active_power_w              0
ambient_temperature_celsius    8631
ghi_irradiance_wm2             8631
dtype: int64
34080
34080
True
True
34080
total_active_power_w              0
ambient_temperature_celsius    3094
ghi_irradiance_wm2             3094
dtype: int64
33984
32736
True
True
33984
total_active_power_w               0
ambient_temperature_celsius    10757
ghi_irradiance_wm2             10757
dtype: int64
31968
31968
True
True
31968
total_active_power_w              0
ambient_temperature_celsius    3982
ghi_irradiance_wm2             3982
dtype: int64
11520
11712
True
True
11520
total_active_power_w              0
ambient_temperature_celsius    1557
ghi_irradiance_wm2             1557
dtype: int64
28128
28896
True
True
28128
total_active_power_w             0
ambient_temperature_celsius    320
ghi_irradiance_wm2             320
dtype: int64
26976
21216
True
True
26976
total_active_power_w              0
ambient_temperature_celsius    8544
ghi_irradiance_wm2             8544
dtype: int64
25248
24960
True
True
25248
total_active_power_w               0
ambient_temperature_celsius    25248
ghi_irradiance_wm2              2828
dtype: int64
19488
19200
True
True
19488
total_active_power_w               0
ambient_temperature_celsius    19488
ghi_irradiance_wm2              3361
dtype: int64
24960
24960
True
True
24960
total_active_power_w               0
ambient_temperature_celsius    24960
ghi_irradiance_wm2              3051
dtype: int64
24960
24960
True
True
24960
total_active_power_w               0
ambient_temperature_celsius    24960
ghi_irradiance_wm2              6705
dtype: int64

/tmp/ipykernel_3319999/2141524626.py:14: DtypeWarning: Columns (0: interpolated_keys_internal_temperature_celsius, 1: interpolated_keys_total_active_power_w, 2: interpolated_keys_total_dc_power_w, 3: interpolated_keys_total_reactive_power_var) have mixed types. Specify dtype option on import or set low_memory=False.
  inv_df = pd.read_csv(inv_filename)

24960
18624
True
True
24960
total_active_power_w               0
ambient_temperature_celsius    24960
ghi_irradiance_wm2              8144
dtype: int64
23904
24960
True
True
23904
total_active_power_w               0
ambient_temperature_celsius    23904
ghi_irradiance_wm2              8578
dtype: int64
24000
24960
True
True
24000
total_active_power_w               0
ambient_temperature_celsius    24000
ghi_irradiance_wm2              3514
dtype: int64
23424
23424
True
True
23424
total_active_power_w               0
ambient_temperature_celsius    23424
ghi_irradiance_wm2              5134
dtype: int64
24096
24000
True
True
24096
total_active_power_w               0
ambient_temperature_celsius    24096
ghi_irradiance_wm2              5392
dtype: int64
24576
24576
True
True
24576
total_active_power_w               0
ambient_temperature_celsius    24576
ghi_irradiance_wm2              4519
dtype: int64
24288
19296
True
True
24288
total_active_power_w               0
ambient_temperature_celsius    24288
ghi_irradiance_wm2              9199
dtype: int64
24192
24192
True
True
24192
total_active_power_w              0
ambient_temperature_celsius    2734
ghi_irradiance_wm2             2734
dtype: int64
24288
24000
True
True
24288
total_active_power_w               0
ambient_temperature_celsius    24288
ghi_irradiance_wm2              5287
dtype: int64
24096
24096
True
True
24096
total_active_power_w               0
ambient_temperature_celsius    24096
ghi_irradiance_wm2              5999
dtype: int64
16320
16320
True
True
16320
total_active_power_w               0
ambient_temperature_celsius    16320
ghi_irradiance_wm2              4019
dtype: int64
23904
23904
True
True
23904
total_active_power_w               0
ambient_temperature_celsius    23904
ghi_irradiance_wm2              6552
dtype: int64
23520
23520
True
True
23520
total_active_power_w              0
ambient_temperature_celsius    4549
ghi_irradiance_wm2             4548
dtype: int64
23328
23328
True
True
23328
total_active_power_w              0
ambient_temperature_celsius    6219
ghi_irradiance_wm2             6219
dtype: int64
18912
18912
True
True
18912
total_active_power_w             0
ambient_temperature_celsius    832
ghi_irradiance_wm2             832
dtype: int64
18816
18816
True
True
18816
total_active_power_w              0
ambient_temperature_celsius    5340
ghi_irradiance_wm2             5340
dtype: int64
18240
18144
True
True
18240
total_active_power_w              0
ambient_temperature_celsius    3535
ghi_irradiance_wm2             3535
dtype: int64
18240
18240
True
True
18240
total_active_power_w             0
ambient_temperature_celsius    531
ghi_irradiance_wm2             531
dtype: int64
17856
17856
True
True
17856
total_active_power_w              0
ambient_temperature_celsius    1506
ghi_irradiance_wm2             1506
dtype: int64
16608
13056
True
True
16608
total_active_power_w              0
ambient_temperature_celsius    3820
ghi_irradiance_wm2             3820
dtype: int64
16800
16800
True
True
16800
total_active_power_w              0
ambient_temperature_celsius    3912
ghi_irradiance_wm2             3912
dtype: int64
9792
9792
True
True
9792
total_active_power_w            0
ambient_temperature_celsius    93
ghi_irradiance_wm2             93
dtype: int64
9792
9792
True
True
9792
total_active_power_w             0
ambient_temperature_celsius    354
ghi_irradiance_wm2             354
dtype: int64
9792
9792
True
True
9792
total_active_power_w             0
ambient_temperature_celsius    102
ghi_irradiance_wm2             102
dtype: int64
9792
9792
True
True
9792
total_active_power_w             0
ambient_temperature_celsius    110
ghi_irradiance_wm2             110
dtype: int64
9792
9792
True
True
9792
total_active_power_w             0
ambient_temperature_celsius    139
ghi_irradiance_wm2             139
dtype: int64
9792
9792
True
True
9792
total_active_power_w             0
ambient_temperature_celsius    163
ghi_irradiance_wm2             163
dtype: int64
9792
9792
True
True
9792
total_active_power_w              0
ambient_temperature_celsius    1485
ghi_irradiance_wm2             1485
dtype: int64
9792
9792
True
True
9792
total_active_power_w              0
ambient_temperature_celsius    1242
ghi_irradiance_wm2             1242
dtype: int64
9792
9792
True
True
9792
total_active_power_w             0
ambient_temperature_celsius    138
ghi_irradiance_wm2             138
dtype: int64
8832
8832
True
True
8832
total_active_power_w             0
ambient_temperature_celsius    177
ghi_irradiance_wm2             177
dtype: int64

,,total_active_power_w,ambient_temperature_celsius,ghi_irradiance_wm2
datetime,ps_id,,,
2024-03-26 00:00:00+00:00,PS_001,0.0,NaN,NaN
2024-03-26 00:15:00+00:00,PS_001,0.0,NaN,NaN
2024-03-26 00:30:00+00:00,PS_001,0.0,NaN,NaN
2024-03-26 00:45:00+00:00,PS_001,0.0,NaN,NaN
2024-03-26 01:00:00+00:00,PS_001,0.0,NaN,NaN
...,...,...,...,...
2025-06-09 22:45:00+00:00,PS_051,0.0,NaN,NaN
2025-06-09 23:00:00+00:00,PS_051,0.0,NaN,NaN
2025-06-09 23:15:00+00:00,PS_051,0.0,NaN,NaN
2025-06-09 23:30:00+00:00,PS_051,0.0,NaN,NaN
2025-06-09 23:45:00+00:00,PS_051,0.0,NaN,NaN

In [15]:
result = result.reset_index()
result = result.dropna()

In [20]:
print(result.isnull().sum(axis=0))

result[(result['total_active_power_w'] > 5e5) & (result['ps_id'] == "PS_001")]

datetime                       0
ps_id                          0
total_active_power_w           0
ambient_temperature_celsius    0
ghi_irradiance_wm2             0
dtype: int64

,datetime,ps_id,total_active_power_w,ambient_temperature_celsius,ghi_irradiance_wm2
242,2024-03-28 12:30:00+00:00,PS_001,8.472500e+05,20.949042,178.682977
243,2024-03-28 12:45:00+00:00,PS_001,1.401623e+06,21.017458,200.058878
244,2024-03-28 13:00:00+00:00,PS_001,1.723051e+06,21.621404,320.811897
245,2024-03-28 13:15:00+00:00,PS_001,1.976655e+06,21.863892,304.648917
246,2024-03-28 13:30:00+00:00,PS_001,1.873885e+06,22.408775,388.260065
...,...,...,...,...,...
42313,2025-06-09 18:15:00+00:00,PS_001,3.581014e+06,21.800001,520.581228
42314,2025-06-09 18:30:00+00:00,PS_001,1.702499e+06,22.500000,268.839993
42315,2025-06-09 18:45:00+00:00,PS_001,1.473602e+06,22.175001,177.866251
42316,2025-06-09 19:00:00+00:00,PS_001,1.139750e+06,21.362500,152.423748
42317,2025-06-09 19:15:00+00:00,PS_001,5.158570e+05,21.158580,126.410888

In [17]:
result.to_parquet(path + "merged.parquet")

In [19]:
df = pd.read_parquet(path + "merged.parquet")
df

,datetime,ps_id,total_active_power_w,ambient_temperature_celsius,ghi_irradiance_wm2
index,,,,,
69,2024-03-26 17:15:00+00:00,PS_001,4.055110e+05,23.000000,96.539849
70,2024-03-26 17:30:00+00:00,PS_001,8.395200e+04,22.960714,53.623824
71,2024-03-26 17:45:00+00:00,PS_001,1.457120e+05,21.767193,14.290886
72,2024-03-26 18:00:00+00:00,PS_001,2.090670e+05,20.596816,33.510205
73,2024-03-26 18:15:00+00:00,PS_001,2.729760e+05,20.431653,50.439045
...,...,...,...,...,...
1206890,2025-06-09 18:30:00+00:00,PS_051,2.235609e+06,34.851252,358.443756
1206891,2025-06-09 18:45:00+00:00,PS_051,2.072260e+06,34.802081,300.378761
1206892,2025-06-09 19:00:00+00:00,PS_051,1.732663e+06,34.334583,245.017496
1206893,2025-06-09 19:15:00+00:00,PS_051,1.545858e+06,34.561507,210.476013
1206894,2025-06-09 19:30:00+00:00,PS_051,0.000000e+00,34.589996,206.910004